sudo: false

language: java
jdk:
  - openjdk11

before_install:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.11.0/z3-4.11.0-x64-glibc-2.31.zip -O /tmp/z3.zip
  - unzip /tmp/z3.zip
  - export PATH=$PATH:$PWD/z3-4.11.0-x64-glibc-2.31/bin/
